### ISSUE TITLE
System.Text.Json.JsonException

### ISSUE THREAD

**Issue by fiala-sns** [yumiris/YouTube.Album.Extract#5]
Alright. I don't know what I am messing up here:
```Please go to https://albumin.miris.design and follow the instructions there, then type the ID in here!
Albumin ID: perfect-cat-139
--------------------------------------------------------------------------------
Please specify a format.
Available formats: flac | lame | opus | vorbis | aac | original
Format: flac
Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $.tracks[0].number | LineNumber: 0 | BytePositionInLine: 97.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.Converters.StringConverter.Read(Utf8JsonReader& , Type , JsonSerializerOptions )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , TCollection& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , Utf8JsonReader& , Exception )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 , JsonTypeInfo , Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 , JsonTypeInfo )
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
   at Albumin.Serialisation.JSON.Hydrate[T](FileInfo source)
   at Albumin.Albums.Albumin.Load(ISerialisation serialisation, FileInfo instructions)
   at Albumin.Program.Invoke()
   at Albumin.Program.Main(String[] args)
```

yt-dlp and flac is in my path, ID from site inserted...
running on Debian 12, amd64
video -> 4cEKAYnxbrk

At first I created 2 totally bad entries orange-starfish-137 and pink-ape-138 because of my inability to read and write. 
Then I tried this:
```
1 | Grassy Plains | 00:00 | 05:12 | | | Lazarus Moment
```
That end up with same error.

Figured that is the missing album and genre I expected to win with this -> nervous-swan-140 :
```
1 | Grassy Plains   | 00:00 | 05:12 | x | Chillout | Lazarus Moment
2 | La Luna         | 05:12 | 09:13 | x | Chillout | VonnBoyd
3 | Until Dawn      | 09:13 | 12:32 | x | Chillout | Infinitum
4 | Panalour        | 12:32 | 15:36 | x | Chillout | Athene
5 | If Onsrfderdfly | 15:36 | 18:31 | x | Chillout | 4lienetic
6 | Atlas           | 18:21 | 22:03 | x | Chillout | Blut Own
7 | Brot            | 22:03 | 26:01 | x | Chillout | Lexis
8 | Pause           | 26:01 | 29:51 | x | Chillout | Unrevel
9 | Flora           | 29:51 | 33:14 | x | Chillout | Ecepta
10 | Endless         | 33:14 | 36:22 | x | Chillout | Maltex
11 | In Space        | 36:22 | 38:27 | x | Chillout | Aurora Night
12 | Reverie         | 38:27 | 41:46 | x | Chillout | Nomyn
13 | Rain            | 41:46 | 43:47 | x | Chillout | Quallm
14 | Other Side      | 43:47 | 46:09 | x | Chillout | GENY.G
15 | Fireflies       | 46:09 | 49:44 | x | Chillout | B. o. O. m.
16 | All The Same    | 49:44 | 51:26 | x | Chillout | IWSYS
```
To get the same error. What I am I missing? (and if it is something stupid I am sorry in advance)

**Comment by MirisWisdom** [comment]
Hey again friend, my thanks for the detailed post! And also apologies for the headache it's causing.

I'm having a look to see what's happening, though in the meantime, if you go to [your album on the website](https://albumin.miris.design/sources/4cEKAYnxbrk/records/140), you will see a `ffmpeg/yt-dlp` button which will give you a [spiffy Bash script](https://albumin.miris.design/shell/nervous-swan-140) for getting the audio files.

**Comment by MirisWisdom** [comment]
Turns out it was an oddly obscure problem with a somehow easy fix.

If you give it a try again like before, all should work as intended -- the problem was on the website, so there's no need to download the program again.

Looking at this project ages later, I can see how it's not too intuitive. If you have any feedback/suggestions which would help with making things clearer and easier to use, please don't hesitate to let me know!

**Comment by MirisWisdom** [comment]
Hey @fiala-sns, I'll be marking the issue as resolved -- thanks again for taking the time to write the detailed report!

**Comment by fiala-sns** [comment]
Hi @MirisWisdom 
Sorry for not responding sooner. I tried it last week but get multiple errors and did not have time. Now I know that those were solely my errors :-) .
1. old binary for yt-dlp on my Debian. 
2. and I was gettin parsing error:
`System.FormatException: String '00:00' was not recognized as a valid DateTime.` 
and did not get why... Only to look back at your web page a reliaze I supplied short string for time (missing leading "00:") this whole time.

So I can confirm that it works great! Thank you for this project!

If I can suggest, please delete my other failed entries for `4cEKAYnxbrk` aside from `fresh-wolverine-145` which works.
